# Generated by Django 2.1.5 on 2019-01-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
