# Generated by Django 2.1.4 on 2019-02-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0002_history_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='memo',
        ),
    ]
