# Generated by Django 2.1.5 on 2019-01-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0002_auto_20190127_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='key',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='key',
            name='room_num',
            field=models.IntegerField(),
        ),
    ]
