# Generated by Django 2.1.4 on 2019-02-15 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0003_remove_history_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='time_back',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
