# Generated by Django 2.1.4 on 2019-02-15 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0004_history_time_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time_cr',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
