# Generated by Django 2.1.5 on 2019-03-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0007_auto_20190305_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='active',
            field=models.CharField(default='Не сдан', max_length=100),
        ),
    ]
